package com.example.sportsprediction.feature_app.domain.model.team_stats

import com.example.sportsprediction.core.util.Constants.emptyString
import com.example.sportsprediction.core.util.Constants.nullDouble
import com.example.sportsprediction.core.util.Constants.nullInteger
import com.example.sportsprediction.feature_app.data.local.entities.event_stats.EventStatsEntity
import com.example.sportsprediction.feature_app.domain.model.general.RoundInfo
import com.example.sportsprediction.feature_app.domain.model.general.Tournament
import java.util.*

data class TeamStats(
    val mainTeamName: String?,
    val mainTeamId: Int?,
    val location: String?,
    val eventId: Int?,
    val date: Date?,
    val roundInfo: RoundInfo?,
    val tournament: Tournament?,
    val tournamentName: String?,

    val fullTimeGoalsTotals: Double?,
    val halfTimeGoalsTotals: Double?,
    val secondHalfGoalsTotals: Double?,
    val fullTimeCornerTotals: Double?,
    val halfTimeCornerTotals: Double?,
    val secondHalfCornerTotals: Double?,
    val fullTimeCardTotals: Double?,
    val halfTimeCardTotals: Double?,
    val secondHalfCardTotals: Double?,
    val fullTimeGoalKeeperSavesTotals: Double?,
    val halfTimeGoalKeeperSavesTotals: Double?,
    val secondHalfGoalKeeperSavesTotals: Double?,
    val fullTimeShotsTotals: Double?,
    val halfTimeShotsTotals: Double?,
    val secondHalfShotsTotals: Double?,
    val fullTimeShotsOnTargetTotals: Double?,
    val halfTimeShotsOnTargetTotals: Double?,
    val secondHalfShotsOnTargetTotals: Double?,
    val fullTimeOffsideTotals: Double?,
    val halfTimeOffsideTotals: Double?,
    val secondHalfOffsideTotals: Double?,

    val fullTimeHomeTeamGoalsTotals: Double?,
    val halfTimeHomeTeamGoalsTotals: Double?,
    val secondHalfHomeTeamGoalsTotals: Double?,
    val fullTimeHomeTeamCornerTotals: Double?,
    val halfTimeHomeTeamCornerTotals: Double?,
    val secondHalfHomeTeamCornerTotals: Double?,
    val fullTimeHomeTeamCardTotals: Double?,
    val halfTimeHomeTeamCardTotals: Double?,
    val secondHalfHomeTeamCardTotals: Double?,
    val fullTimeHomeTeamGoalKeeperSavesTotals: Double?,
    val halfTimeHomeTeamGoalKeeperSavesTotals: Double?,
    val secondHalfHomeTeamGoalKeeperSavesTotals: Double?,
    val fullTimeHomeTeamShotsTotals: Double?,
    val halfTimeHomeTeamShotsTotals: Double?,
    val secondHalfHomeTeamShotsTotals: Double?,
    val fullTimeHomeTeamShotsOnTargetTotals: Double?,
    val halfTimeHomeTeamShotsOnTargetTotals: Double?,
    val secondHalfHomeTeamShotsOnTargetTotals: Double?,
    val fullTimeHomeTeamOffsideTotals: Double?,
    val halfTimeHomeTeamOffsideTotals: Double?,
    val secondHalfHomeTeamOffsideTotals: Double?,

    val fullTimeAwayTeamGoalsTotals: Double?,
    val halfTimeAwayTeamGoalsTotals: Double?,
    val secondHalfAwayTeamGoalsTotals: Double?,
    val fullTimeAwayTeamCornerTotals: Double?,
    val halfTimeAwayTeamCornerTotals: Double?,
    val secondHalfAwayTeamCornerTotals: Double?,
    val fullTimeAwayTeamCardTotals: Double?,
    val halfTimeAwayTeamCardTotals: Double?,
    val secondHalfAwayTeamCardTotals: Double?,
    val fullTimeAwayTeamGoalKeeperSavesTotals: Double?,
    val halfTimeAwayTeamGoalKeeperSavesTotals: Double?,
    val secondHalfAwayTeamGoalKeeperSavesTotals: Double?,
    val fullTimeAwayTeamShotsTotals: Double?,
    val halfTimeAwayTeamShotsTotals: Double?,
    val secondHalfAwayTeamShotsTotals: Double?,
    val fullTimeAwayTeamShotsOnTargetTotals: Double?,
    val halfTimeAwayTeamShotsOnTargetTotals: Double?,
    val secondHalfAwayTeamShotsOnTargetTotals: Double?,
    val fullTimeAwayTeamOffsideTotals: Double?,
    val halfTimeAwayTeamOffsideTotals: Double?,
    val secondHalfAwayTeamOffsideTotals: Double?,

    val fullTimeMatchResult: Double?,
    val halfTimeMatchResult: Double?,
    val secondHalfMatchResult: Double?,
    val fullTimeCornerResult: Double?,
    val halfTimeCornerResult: Double?,
    val secondHalfCornerResult: Double?,
    val fullTimeCardResult: Double?,
    val halfTimeCardResult: Double?,
    val secondHalfCardResult: Double?,
    val fullTimeGoalKeeperSavesResult: Double?,
    val halfTimeGoalKeeperSavesResult: Double?,
    val secondHalfGoalKeeperSavesResult: Double?,
    val fullTimeShotsResult: Double?,
    val halfTimeShotsResult: Double?,
    val secondHalfShotsResult: Double?,
    val fullTimeShotsOnTargetResult: Double?,
    val halfTimeShotsOnTargetResult: Double?,
    val secondHalfShotsOnTargetResult: Double?,
    val fullTimeOffsideResult: Double?,
    val halfTimeOffsideResult: Double?,
    val secondHalfOffsideResult: Double?

) {
    fun toTeamStatsEntity(
        homeTeamName: String?,
        homeTeamId: Int?,
        awayTeamName: String?,
        awayTeamId: Int?,
        startTimestamp: Int?
    ): EventStatsEntity {
        return EventStatsEntity(
            null,
            mainTeamName ?: emptyString,
            mainTeamId ?: nullInteger,
            homeTeamName ?: emptyString,
            homeTeamId ?: nullInteger,
            awayTeamName ?: emptyString,
            awayTeamId ?: nullInteger,
            if (mainTeamName == homeTeamName) awayTeamName else homeTeamName ?: emptyString,
            if (mainTeamId == homeTeamId) awayTeamId else homeTeamId ?: nullInteger,
            startTimestamp ?: nullInteger,
            location ?: emptyString,
            eventId ?: nullInteger,
            date ?: Date(),
            roundInfo,
            tournament,
            tournamentName ?: emptyString,
            fullTimeGoalsTotals ?: nullDouble,
            halfTimeGoalsTotals ?: nullDouble,
            secondHalfGoalsTotals ?: nullDouble,
            fullTimeCornerTotals ?: nullDouble,
            halfTimeCornerTotals ?: nullDouble,
            secondHalfCornerTotals ?: nullDouble,
            fullTimeCardTotals ?: nullDouble,
            halfTimeCardTotals ?: nullDouble,
            secondHalfCardTotals ?: nullDouble,
            fullTimeGoalKeeperSavesTotals ?: nullDouble,
            halfTimeGoalKeeperSavesTotals ?: nullDouble,
            secondHalfGoalKeeperSavesTotals ?: nullDouble,
            fullTimeShotsTotals ?: nullDouble,
            halfTimeShotsTotals ?: nullDouble,
            secondHalfShotsTotals ?: nullDouble,
            fullTimeShotsOnTargetTotals ?: nullDouble,
            halfTimeShotsOnTargetTotals ?: nullDouble,
            secondHalfShotsOnTargetTotals ?: nullDouble,
            fullTimeOffsideTotals ?: nullDouble,
            halfTimeOffsideTotals ?: nullDouble,
            secondHalfOffsideTotals ?: nullDouble,
            fullTimeHomeTeamGoalsTotals ?: nullDouble,
            halfTimeHomeTeamGoalsTotals ?: nullDouble,
            secondHalfHomeTeamGoalsTotals ?: nullDouble,
            fullTimeHomeTeamCornerTotals ?: nullDouble,
            halfTimeHomeTeamCornerTotals ?: nullDouble,
            secondHalfHomeTeamCornerTotals ?: nullDouble,
            fullTimeHomeTeamCardTotals ?: nullDouble,
            halfTimeHomeTeamCardTotals ?: nullDouble,
            secondHalfHomeTeamCardTotals ?: nullDouble,
            fullTimeHomeTeamGoalKeeperSavesTotals ?: nullDouble,
            halfTimeHomeTeamGoalKeeperSavesTotals ?: nullDouble,
            secondHalfHomeTeamGoalKeeperSavesTotals ?: nullDouble,
            fullTimeHomeTeamShotsTotals ?: nullDouble,
            halfTimeHomeTeamShotsTotals ?: nullDouble,
            secondHalfHomeTeamShotsTotals ?: nullDouble,
            fullTimeHomeTeamShotsOnTargetTotals ?: nullDouble,
            halfTimeHomeTeamShotsOnTargetTotals ?: nullDouble,
            secondHalfHomeTeamShotsOnTargetTotals ?: nullDouble,
            fullTimeHomeTeamOffsideTotals ?: nullDouble,
            halfTimeHomeTeamOffsideTotals ?: nullDouble,
            secondHalfHomeTeamOffsideTotals ?: nullDouble,
            fullTimeAwayTeamGoalsTotals ?: nullDouble,
            halfTimeAwayTeamGoalsTotals ?: nullDouble,
            secondHalfAwayTeamGoalsTotals ?: nullDouble,
            fullTimeAwayTeamCornerTotals ?: nullDouble,
            halfTimeAwayTeamCornerTotals ?: nullDouble,
            secondHalfAwayTeamCornerTotals ?: nullDouble,
            fullTimeAwayTeamCardTotals ?: nullDouble,
            halfTimeAwayTeamCardTotals ?: nullDouble,
            secondHalfAwayTeamCardTotals ?: nullDouble,
            fullTimeAwayTeamGoalKeeperSavesTotals ?: nullDouble,
            halfTimeAwayTeamGoalKeeperSavesTotals ?: nullDouble,
            secondHalfAwayTeamGoalKeeperSavesTotals ?: nullDouble,
            fullTimeAwayTeamShotsTotals ?: nullDouble,
            halfTimeAwayTeamShotsTotals ?: nullDouble,
            secondHalfAwayTeamShotsTotals ?: nullDouble,
            fullTimeAwayTeamShotsOnTargetTotals ?: nullDouble,
            halfTimeAwayTeamShotsOnTargetTotals ?: nullDouble,
            secondHalfAwayTeamShotsOnTargetTotals ?: nullDouble,
            fullTimeAwayTeamOffsideTotals ?: nullDouble,
            halfTimeAwayTeamOffsideTotals ?: nullDouble,
            secondHalfAwayTeamOffsideTotals ?: nullDouble,
            fullTimeMatchResult ?: nullDouble,
            halfTimeMatchResult ?: nullDouble,
            secondHalfMatchResult ?: nullDouble,
            fullTimeCornerResult ?: nullDouble,
            halfTimeCornerResult ?: nullDouble,
            secondHalfCornerResult ?: nullDouble,
            fullTimeCardResult ?: nullDouble,
            halfTimeCardResult ?: nullDouble,
            secondHalfCardResult ?: nullDouble,
            fullTimeGoalKeeperSavesResult ?: nullDouble,
            halfTimeGoalKeeperSavesResult ?: nullDouble,
            secondHalfGoalKeeperSavesResult ?: nullDouble,
            fullTimeShotsResult ?: nullDouble,
            halfTimeShotsResult ?: nullDouble,
            secondHalfShotsResult ?: nullDouble,
            fullTimeShotsOnTargetResult ?: nullDouble,
            halfTimeShotsOnTargetResult ?: nullDouble,
            secondHalfShotsOnTargetResult ?: nullDouble,
            fullTimeOffsideResult ?: nullDouble,
            halfTimeOffsideResult ?: nullDouble,
            secondHalfOffsideResult ?: nullDouble
        )
    }
}
