package com.example.sportsprediction.feature_app.ui.presentation.view_model.states

import com.example.sportsprediction.core.util.Constants.emptyString
import com.example.sportsprediction.core.util.Constants.NoValue_Double
import com.example.sportsprediction.core.util.Constants.nullDouble
import com.example.sportsprediction.feature_app.data.local.entities.event_stats.EventStatsEntity
import java.util.*


data class TeamEventsStatsState (
    val teamEventsStats: EventStatsEntity? =
        EventStatsEntity(null,
            emptyString,
            0,
            emptyString,
            0,
            emptyString,
            0,
            emptyString,
            0,
            0,
            emptyString,
            0,
            Date(),
            null,
            null,
            null,
            NoValue_Double,
            NoValue_Double,
            NoValue_Double,
            NoValue_Double,
            NoValue_Double,
            NoValue_Double,
            NoValue_Double,
            NoValue_Double,
            NoValue_Double,
            NoValue_Double,
            NoValue_Double,
            NoValue_Double,
            NoValue_Double,
            NoValue_Double,
            NoValue_Double,
            NoValue_Double,
            NoValue_Double,
            NoValue_Double,
            NoValue_Double,
            NoValue_Double,
            NoValue_Double,
            NoValue_Double,
            NoValue_Double,
            NoValue_Double,
            NoValue_Double,
            NoValue_Double,
            NoValue_Double,
            NoValue_Double,
            NoValue_Double,
            NoValue_Double,
            NoValue_Double,
            NoValue_Double,
            NoValue_Double,
            NoValue_Double,
            NoValue_Double,
            NoValue_Double,
            NoValue_Double,
            NoValue_Double,
            NoValue_Double,
            NoValue_Double,
            NoValue_Double,
            NoValue_Double,
            NoValue_Double,
            NoValue_Double,
            NoValue_Double,
            NoValue_Double,
            NoValue_Double,
            NoValue_Double,
            NoValue_Double,
            NoValue_Double,
            NoValue_Double,
            NoValue_Double,
            NoValue_Double,
            NoValue_Double,
            NoValue_Double,
            NoValue_Double,
            NoValue_Double,
            NoValue_Double,
            NoValue_Double,
            NoValue_Double,
            NoValue_Double,
            NoValue_Double,
            NoValue_Double,
            nullDouble,
            nullDouble,
            nullDouble,
            nullDouble,
            nullDouble,
            nullDouble,
            nullDouble,
            nullDouble,
            nullDouble,
            nullDouble,
            nullDouble,
            nullDouble,
            nullDouble,
            nullDouble,
            nullDouble,
            nullDouble,
            nullDouble,
            nullDouble,
            nullDouble,
            nullDouble,
            nullDouble
        ),
    val isLoading: Boolean = false
)